<h1><?php echo $this->titulo?></h1>
<?php
$form = $this->form;
$form->prepare();
//$a=$this->$datos['rut'];
/*
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('application/formulario/recibe'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');
*/

$form->setAttributes(array(
    'action' => $this->url.'/materiales/buscar/mostrar',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>

<div class="form_element">

<?php
    $palabra = $form->get('palabra');
    echo $formLabel->openTag().$palabra->getOption('label')." ";
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
	echo $this->formInput($palabra);
?>

</div>
<div class="form_element">

<?php
    $parametro = $form->get('parametro');
    echo $formLabel->openTag().$parametro->getLabel();
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
	echo $this->formSelect($parametro);
?>

</div>
<div class="form_element">

<?php
    $idioma = $form->get('idioma');
    echo $formLabel->openTag().$idioma->getLabel();
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
	echo $this->formSelect($idioma);
?>

</div>

<div class="form_element">

<?php
    $tipo = $form->get('tipo');
    echo $formLabel->openTag().$tipo->getLabel();
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
	echo $this->formSelect($tipo);
?>

</div>

<div class="form_element">

<?php

    echo $this->formElement($form->get('buscar'));
?>

</div>


<?php echo $this->form()->closeTag() ?>