<div class="row-fluid titulo" style="background:#003277">
<div class="container">
<h4 style="color:white"><?php echo $this->titulo?></h4>
</div>
</div>
<div class="row-fluid">
<br>
<br>
</div>
<div class="container well" >
<?php
$form = $this->form;
$form->prepare();
//$a=$this->$datos['rut'];
/*
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('application/formulario/recibe'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');
*/

$form->setAttributes(array(
    'action' => $this->url.'/usuarios/editatipo/editar',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>

<div class="form_element">

<?php
    $nombre_tipo = $form->get('buscar_nombre_tipo');
    echo $formLabel->openTag().$nombre_tipo->getOption('label')." ";
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
	echo $this->formInput($nombre_tipo);
    echo $this->formElement($form->get('buscar'));
?>

</div>


<?php echo $this->form()->closeTag() ?>

</div>