<h1><?php echo $this->titulo?></h1>
<?php
$form = $this->form;
$form->prepare();
/*
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('application/formulario/recibe'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');
*/

$form->setAttributes(array(
    'action' => $this->url.'/usuarios/gestion/guardacarrera',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>

<div class="form_element">

<?php
    $carrera = $form->get('nombre_carrera');
    echo $formLabel->openTag().$carrera->getOption('label')." ";
    echo $this->formElementErrors($carrera);
    echo $formLabel->closeTag();
	echo $this->formInput($carrera);
?>

<?php
    $descripcion = $form->get('descripcion_carrera');
    echo $formLabel->openTag().$descripcion->getOption('label')." ";
    echo $this->formElementErrors($descripcion);
    echo $formLabel->closeTag();
	echo $this->formTextarea($descripcion);
?>


</div>

<hr />

<?php echo $this->formElement($form->get('send')) ?>

<?php echo $this->form()->closeTag() ?>