<div class="row-fluid titulo" >
<div class="container" style="overflow-x:hidden">
<h4 style="color:white"><?php echo $this->titulo?></h4>
</div>
</div>
<div class="row-fluid">
<br>
<br>
</div>
<div class="container" >
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.'/materiales/ingreso/guardal',
    'method' => 'post'
));

// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>

<div class="row-fluid">
        <div class="span6 well" style="padding-left:4%; padding-bottom:125px">

<?php
    $codigo = $form->get('codigo');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>




<?php
    $titulo = $form->get('titulo');
    echo $formLabel->openTag().$titulo->getOption('label')." ";
    echo $this->formElementErrors($titulo);
    echo $formLabel->closeTag();
	echo $this->formInput($titulo);
?>



<?php
    $autor = $form->get('autor');
    echo $formLabel->openTag().$autor->getOption('label')." ";
    echo $this->formElementErrors($autor);
    echo $formLabel->closeTag();
	echo $this->formInput($autor);
?>



<?php
    $edicion = $form->get('edicion');
    echo $formLabel->openTag().$edicion->getOption('label')." ";
    echo $this->formElementErrors($edicion);
    echo $formLabel->closeTag();
	echo $this->formInput($edicion);
?>



<?php
	$anio = $form->get('anio');
    echo $formLabel->openTag().$anio->getOption('label')." ";
    echo $formLabel->closeTag();
	echo $this->formInput($anio);
    
?>



<?php
    $numero_paginas = $form->get('numero_paginas');
    echo $formLabel->openTag().$numero_paginas->getOption('label')." ";
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
	 echo $this->formInput($numero_paginas);
?>




<?php
    $editorial = $form->get('editorial');
    echo $formLabel->openTag().$editorial->getOption('label')." ";
    //echo $this->formElementErrors($pass);
    echo $formLabel->closeTag();
    echo $this->formInput($editorial);
?>


<?php
    $tomo= $form->get('tomo');
    echo $formLabel->openTag().$tomo->getOption('label')." ";
    //echo $this->formElementErrors($pass);
    echo $formLabel->closeTag();
    echo $this->formInput($tomo);
?>

<?php
    $volumen = $form->get('volumen');
    echo $formLabel->openTag().$volumen->getOption('label')." ";
    //echo $this->formElementErrors($pass);
    echo $formLabel->closeTag();
    echo $this->formInput($volumen);
?>
</div>
<div class="span6 well" style="padding-left:4%">
<?php
    $descripcion = $form->get('descripcion');
    echo $formLabel->openTag().$descripcion->getOption('label')." ";
    //echo $this->formElementErrors($pass);
    echo $formLabel->closeTag();
    echo $this->formTextarea($descripcion);
?>
<br>
<br>
<?php
    $isbn = $form->get('isbn');
    echo $formLabel->openTag().$isbn->getOption('label')." ";
    //echo $this->formElementErrors($pass);
    echo $formLabel->closeTag();
    echo $this->formInput($isbn);
?>
<br>
<br>
<?php
    $idioma = $form->get('idioma');
    echo $formLabel->openTag().$idioma->getLabel();
    //echo $this->formElementErrors($lenguaje);
    echo $formLabel->closeTag();
    echo $this->formSelect($idioma);
?>

<br>
<br>
<?php
    $date = $form->get('date');
    echo $formLabel->openTag().$date->getLabel();
    //echo $formLabel->openTag().$date->getOption('label')." ";
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($date);
?>

<br>
<br>
<?php
   $fono = $form->get('pal_clav');
    echo $formLabel->openTag().$fono->getOption('label')." ";
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
	echo $this->formTextarea($fono);
?>

<br>
<br>
<?php
    $numero = $form->get('numero');
    echo $formLabel->openTag().$numero->getLabel();
    //echo $formLabel->openTag().$date->getOption('label')." ";
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($numero);
?>

<br>
<br>
<?php
    $copia = $form->get('copia');
    echo $formLabel->openTag().$copia->getLabel();
    echo $formLabel->closeTag();
    echo $this->formRadio($copia);
    ?>
<br>
<br>
<?php echo $this->formElement($form->get('send')) ?>
</div>
</div>
</div>



<?php echo $this->form()->closeTag() ?>
