<h1><?php echo $this->titulo?></h1>
<h1><?php echo $this->a?></h1>
<?php
$form = $this->form;
$form->prepare();
/*
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('application/formulario/recibe'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');
*/

$form->setAttributes(array(
    'action' => $this->url.'/auth/login/index',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>

<div class="form_element">

<?php
    $usuario = $form->get('usuario');
    echo $formLabel->openTag().$usuario->getLabel();
    echo $this->formElementErrors($usuario);
    echo $formLabel->closeTag();
	echo $this->formInput($usuario);
?>

<?php
    $pass = $form->get('pass');
    echo $formLabel->openTag().$pass->getLabel();
    echo $this->formElementErrors($pass);
    echo $formLabel->closeTag();
	echo $this->formInput($pass);
?>

</div>

<hr />

<?php echo $this->formElement($form->get('send')) ?>

<?php echo $this->form()->closeTag() ?>